source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
inhibit_all_warnings!
pod 'SDWebImage'
pod 'SSKeychain'
pod 'pop'
pod 'JSONModel'
pod 'AFNetworking'
pod 'RETableViewManager'
pod 'HHRouter', :git => 'https://github.com/CupinnCoder/HHRouter.git'
pod 'JDStatusBarNotification', :git => 'https://github.com/CupinnCoder/JDStatusBarNotification.git'
pod 'NJKWebViewProgress'
pod 'GPUImage'
pod 'FMDB'
pod 'DateTools'
pod 'ActionSheetPicker-3.0'
pod 'EGOCache'
pod 'JTCalendar'
pod 'PINRemoteImage','~>3.0.0-beta.4'
pod 'GKFadeNavigationController‘
pod 'Masonry'
pod 'JSONModel'
pod 'SVProgressHUD'
pod 'MyBBTableViewManager', :git => 'https://github.com/CupinnCoder/MyBBTableViewManager'
pod 'AnimatedGIFImageSerialization'
pod 'YYKit'
